# ./prometheus.yml - minimal example
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-scrape
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Example service job - add your services here
  - job_name: 'jobber_services'
    static_configs:
      - targets: ['localhost:9090']  # replace with real targets like "service:metrics_port"
